name: Build and Test

on: [push]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --unshallow

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 6.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
            versionSpec: '5.x'
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Install dependencies
        run: dotnet restore ./NServiceBus.Saga.Demo.sln

      - name: Build .NET solution
        env:
          SemVer: ${{ steps.gitversion.outputs.semVer }}
        run: |
          dotnet build ./NServiceBus.Saga.Demo.sln --configuration Release --no-restore

      - name: Test .NET solution
        run: |
          dotnet test ./NServiceBus.Saga.Demo.sln --configuration Release --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
